import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Index Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{
        margin: 0,
        padding: 0,
        // border:"2px solid red",
        // display:"flex",
        // alignItems:"center",
        // justifyContent:"center",
        // height:"100vh",
      }}>
        {children}
      </body>
    </html>
  );
}
